/* Generated By:JJTree: Do not edit this line. ASTPostIncDecExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTPostIncDecExpression extends SimpleNode {
	private String op;
	private String name;
	private String type;
	public String getOp() {
		return op;
	}

	public void setOp(String op) {
		this.op = op;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public ASTPostIncDecExpression(int id) {
		super(id);
	}

  public ASTPostIncDecExpression(Eg2 p, int id) {
    super(p, id);
  }

  public String genInter() {
	  String content = "\n"
			  + type + ":"
			  + name + " "
			  + "= "
			  + type + ":"
			  + name + " "
			  + op + " 1";
	  return content;
  }
}
/* JavaCC - OriginalChecksum=f87c8e3da11360e8b2b5655aea346462 (do not edit this line) */
