import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTAndExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAndExpression extends SimpleNode {
  public ASTAndExpression(int id) {
    super(id);
  }

  public ASTAndExpression(Eg2 p, int id) {
    super(p, id);
  }

  public int genInter(int paraL, int paraR) throws IOException {
		content = "\n@t"
				+ Integer.toString(genPara()) + " = "
				+ " @t" + Integer.toString(paraL)
				+ " & "
				+ " @t" + Integer.toString(paraR);
		writeInter();
		return para;
  }
}
/* JavaCC - OriginalChecksum=908e43544b13ad340dc691e908cf2441 (do not edit this line) */
