import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTBreakStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBreakStatement extends SimpleNode {
  public ASTBreakStatement(int id) {
    super(id);
  }

  public ASTBreakStatement(Eg2 p, int id) {
    super(p, id);
  }
  
  public int genInter() throws IOException {
	  int label = breakLabel.get(breakLabel.size() - 1);
	  //breakLabel.remove(breakLabel.size() - 1);
	  content = "goto @L" + Integer.toString(label)
			  + "\n";
	  writeInter();
	  return para;
  }

}
/* JavaCC - OriginalChecksum=d307b5dd97f39d16629f097cfce8b30b (do not edit this line) */
