import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTConditionalAndExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConditionalAndExpression extends SimpleNode {
  public ASTConditionalAndExpression(int id) {
    super(id);
  }

  public ASTConditionalAndExpression(Eg2 p, int id) {
    super(p, id);
  }
  
  public int genInter(int paraL, int paraR) throws IOException {
	  content = "if @t"
				+ Integer.toString(paraL)
				+ " != 0 " 
				+ " goto @L" + Integer.toString(genLabel())
				+ "\ngoto @L" + Integer.toString(genLabel());
	  content += "\n@L"
				+ Integer.toString(genOldLabel())
				+ ": if @t"
				+ Integer.toString(paraR)
				+ " != 0 " 
				+ " goto @L" + Integer.toString(genLabel())
				+ "\n@L"
				+ Integer.toString(genOldLabel())
				+ ":"
				+ " @t" + Integer.toString(genPara())
				+ " = 0 "
				+ "\ngoto @L" + Integer.toString(genLabel())
				+ "\n@L" + Integer.toString(genOldLabel())
				+ ":"
				+ " @t" + Integer.toString(para)
				+ " = 1 "
				+ "\n@L" + Integer.toString(genOldLabel())
				+ ": ";
	  writeInter();
	  return para;
  }

}
/* JavaCC - OriginalChecksum=d781d0085334c1a7aa64a7a1b7173818 (do not edit this line) */
