import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTConditionalOrExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConditionalOrExpression extends SimpleNode {
  public ASTConditionalOrExpression(int id) {
    super(id);
  }

  public ASTConditionalOrExpression(Eg2 p, int id) {
    super(p, id);
  }
  
  public String genInter() {
	  return null;
  }

  public int genInter(int paraL, int paraR) throws IOException {
	  content = "if @t"
				+ Integer.toString(paraL)
				+ " == 0 " 
				+ " goto @L" + Integer.toString(genLabel())
				+ "\ngoto @L" + Integer.toString(genLabel());
	  content += "\n@L"
				+ Integer.toString(genOldLabel())
				+ ": if @t"
				+ Integer.toString(paraR)
				+ " == 0 " 
				+ " goto @L" + Integer.toString(genLabel())
				+ "\n@L" + Integer.toString(genOldLabel())
				+ ":"
				+ " @t" + Integer.toString(genPara())
				+ " = 1"
				+ "\ngoto @L" + Integer.toString(genLabel())
				+ "\n@L" + Integer.toString(genOldLabel()) + ":"
				+ " @t" + Integer.toString(para)
				+ " = 0"
				+ "\n@L" + Integer.toString(genOldLabel()) + ": ";
	  writeInter();
	  return para;
  }
}
/* JavaCC - OriginalChecksum=02c491c8be7d4f81173c21e7f1dfebb2 (do not edit this line) */
