import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTContinueStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTContinueStatement extends SimpleNode {
  public ASTContinueStatement(int id) {
    super(id);
  }

  public ASTContinueStatement(Eg2 p, int id) {
    super(p, id);
  }

  public int genInter() throws IOException {
	  int label = continueLabel.get(breakLabel.size() - 1);
	  //continueLabel.remove(breakLabel.size() - 1);
	  content = "goto @L" + Integer.toString(label)
			  + "\n";
	  writeInter();
	  return para;
  }
}
/* JavaCC - OriginalChecksum=eb4845eba9c5957029dcf9267a2ed827 (do not edit this line) */
