import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTEqualityExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEqualityExpression extends SimpleNode {
	private String op;
	
	
	public String getOp() {
		return op;
	}

	public void setOp(String op) {
		this.op = op;
	}

	public ASTEqualityExpression(int id) {
		super(id);
	}

	public ASTEqualityExpression(Eg2 p, int id) {
		super(p, id);
	}
	
	public int genInter(int paraL, int paraR) throws IOException {
		content = "if @t"
				+ Integer.toString(paraL)
				+ " " + op
				+ " @t" + Integer.toString(paraR)
				+ " goto @L" + Integer.toString(genLabel())
				+ "\ngoto @L" + Integer.toString(genLabel());
		content += "\n@L"
				+ Integer.toString(genOldLabel())
				+ ": @t" + Integer.toString(genPara())
				+ " = 1\n"
				+ "@L"
				+ Integer.toString(genOldLabel())
				+ ": @t" + Integer.toString(para)
				+ " = 0";
		writeInter();
		return para;
	}

}
/* JavaCC - OriginalChecksum=20e299ebfa8dc5bd75f93106585269c0 (do not edit this line) */
