import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTExclusiveOrExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExclusiveOrExpression extends SimpleNode {
  public ASTExclusiveOrExpression(int id) {
    super(id);
  }

  public ASTExclusiveOrExpression(Eg2 p, int id) {
    super(p, id);
  }

  public int genInter(int paraL, int paraR) throws IOException {
		content = "@t"
				+ Integer.toString(genPara()) + " = "
				+ " @t" + Integer.toString(paraL)
				+ " ^ "
				+ " @t" + Integer.toString(paraR)
				+ "\n";
		writeInter();
		return para;
  }
}
/* JavaCC - OriginalChecksum=b028ec8b3499f3eaf9f8f22ac066704f (do not edit this line) */
