import java.io.IOException;

import com.sun.org.apache.xml.internal.security.algorithms.implementations.IntegrityHmac.IntegrityHmacSHA512;

/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfStatement extends SimpleNode {
  public ASTIfStatement(int id) {
    super(id);
  }

  public ASTIfStatement(Eg2 p, int id) {
    super(p, id);
  }

  public int genInter(int paraL, int paraR) throws IOException {
	  content = "\nt" + Integer.toString(genPara()) + " = t" + Integer.toString(paraR)
			  + "\nif t" + Integer.toString(para) + " == 0 goto L" + Integer.toString(genLabel());
	  writeInter();
	  return para;
  }
  public void genTailLabel() throws IOException {
	  content = "\nL" + Integer.toString(genOldLabel()) + ":";
	  writeInter();
  }
}
/* JavaCC - OriginalChecksum=fbd922bf00499479df542d2a088931a1 (do not edit this line) */
