import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTSimpleUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSimpleUnaryExpression extends SimpleNode {
	private String op;
	
	public String getOp() {
		return op;
	}

	public void setOp(String op) {
		this.op = op;
	}

	public ASTSimpleUnaryExpression(int id) {
	    super(id);
	}

	public ASTSimpleUnaryExpression(Eg2 p, int id) {
		super(p, id);
	}
	
	public int genInter(int prarL, int paraR) throws IOException {
		content = "\n@t"
				+ Integer.toString(para)
				+ " " + op
				+ " " + paraR;
		writeInter();
		return para;
	}

}
/* JavaCC - OriginalChecksum=bab307e034a02bec5c7db72856fa7dd4 (do not edit this line) */
