/* Generated By:JJTree: Do not edit this line. ASTStructParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStructParameter extends SimpleNode {
	public String name;
	public String type;
	
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	
  public ASTStructParameter(int id) {
    super(id);
  }

  public ASTStructParameter(Eg2 p, int id) {
    super(p, id);
  }
  
  
  public String genInter() {
	  String content = name
			  + ":"
			  + type
			  + " ";
	  return content;
  }


}
/* JavaCC - OriginalChecksum=d0e7e2891aab723cda17c72431707906 (do not edit this line) */
