import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUnaryExpression extends SimpleNode {
	private String op;
	
	public String getOp() {
		return op;
	}

	public void setOp(String op) {
		this.op = op;
	}

	public ASTUnaryExpression(int id) {
		super(id);
	}

	public ASTUnaryExpression(Eg2 p, int id) {
		super(p, id);
	}
	
	public int genInter(int paraL, int paraR) throws IOException {
		content = "\nt"
				+ Integer.toString(para)
				+ " 0 " + op
				+ " " + paraR;
		writeInter();
		return para;
	}
  
}
/* JavaCC - OriginalChecksum=cb1449db1ced9f6442fcad6cb1e5eb54 (do not edit this line) */
